# Generated by Django 2.0.4 on 2018-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_signupmodel_idformongo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='objectivestatement',
            field=models.CharField(max_length=1000),
        ),
    ]
