# Generated by Django 2.0.4 on 2018-04-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180426_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperiencemodel',
            name='feedbackforjob',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
